apiVersion: skaffold/v4beta4
kind: Config
build:
  local:
    push: true
    useDockerCLI: true
  artifacts:
  - image: 192.168.0.10:32000/app-python
    context: ./apps/app-python/
    docker:
      dockerfile: ./apps/app-python/Dockerfile
  - image: 192.168.0.10:32000/app-go
    context: ./apps/app-go/
    docker:
      dockerfile: ./apps/app-go/Dockerfile
  - image: 192.168.0.10:32000/app-openresty
    context: ./apps/app-openresty/
    docker:
      dockerfile: ./apps/app-openresty/Dockerfile
  - image: 192.168.0.10:32000/middleware-postgresql
    context: ./apps/middleware-postgresql/
    docker:
      dockerfile: ./apps/middleware-postgresql/Dockerfile


profiles:
- name: base
  manifests:
    kustomize:
      paths:
        - envs/base
- name: dev
  manifests:
    kustomize:
      paths:
        - envs/dev
- name: prod
  manifests:
    kustomize:
      paths:
        - envs/prod
