# npm install -g yarn

# https://marmelab.com/react-admin/Tutorial.html
# yarn create vite app-front-admin --template react-ts
# cd app-front-admin
# yarn add react-admin ra-data-json-server


dev:
	@yarn dev
