apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

# 共通ラベルを設定
# commonLabels:
#   app: kustomize-example

resources:
- storage.yaml
- app-python.yaml
- app-go.yaml
- app-openresty.yaml
- middleware-nats-jet-stream.yaml  # stream の他に object storage key value store など 一人三役
- middleware-fulltextsearch.yaml
- middleware-postgresql.yaml
- middleware-gitea.yaml
# - openlinage: linageの標準化を目指すもの marquez: openlinage のリファレンス実装
- debug-busybox.yaml
