apiVersion: v1
kind: Service
metadata:
  name: middleware-postgresql
spec:
  selector:
    app: middleware-postgresql
  ports:
    - protocol: TCP
      port: 5432
      targetPort: 5432


---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: middleware-postgresql
spec:
  selector:
    matchLabels:
      app: middleware-postgresql
  template:
    metadata:
      labels:
        app: middleware-postgresql
    spec:
      containers:
      - name: middleware-postgresql
        # image: postgres:14
        image: 192.168.0.10:32000/middleware-postgresql
        ports:
          - containerPort: 5432
        env:
        - name: POSTGRES_DB
          value: "postgres"
        - name: POSTGRES_USER
          value: "postgres"
        - name: POSTGRES_PASSWORD
          value: "postgres"
        volumeMounts:
        - mountPath: /var/lib/postgresql/data
          subPath: postgres
          name: data-volume
      volumes:
      - name: data-volume
        persistentVolumeClaim:
          claimName: disk-shared
