apiVersion: v1
kind: Service
metadata:
  name: middleware-gitea
spec:
  ports:
  - port: 3000
    targetPort: 3000
    name: http
  # - port: 22
  #   targetPort: 22
  #   name: ssh
  type: LoadBalancer
  selector:
    app: middleware-gitea
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: middleware-gitea
spec:
  selector:
    matchLabels:
      app: middleware-gitea
  template:
    metadata:
      labels:
        app: middleware-gitea
    spec:
      containers:
      - name: middleware-gitea
        image: gitea/gitea:1.19.0
        ports:
        - containerPort: 3000
          name: gitea
        # - containerPort: 22
        #   name: git-ssh
        env:
        - name: USER_UID
          value: "1000"
        - name: USER_GID
          value: "1000"
        - name: GITEA__database__DB_TYPE
          value: "postgres"
        - name: GITEA__database__HOST
          value: "middleware-postgresql:5432"
        - name: GITEA__database__NAME
          value: "postgres"
        - name: GITEA__database__USER
          value: "postgres"
        - name: GITEA__database__PASSWD
          value: "postgres"
        - name: GITEA__DATABASE__SCHEMA
          value: "gitea"
        - name: ISSUE_INDEXER_TYPE
          value: "meilisearch"
        - name: ISSUE_INDEXER_CONN_STR
          value: "middleware-fulltextsearch:3000"
        volumeMounts:
        - mountPath: /data
          subPath: gitea
          name: data-volume
      volumes:
      - name: data-volume
        persistentVolumeClaim:
          claimName: disk-shared

# gitea:
#     image: gitea/gitea:1.19.0
#     # container_name: gitea
#     environment:
#       - USER_UID=1000
#       - USER_GID=1000
#       - GITEA__database__DB_TYPE=postgres
#       - GITEA__DATABASE__SCHEMA=gitea
#       - GITEA__database__HOST=db:5432
#       - GITEA__database__NAME=gitea
#       - GITEA__database__USER=gitea
#       - GITEA__database__PASSWD=gitea
#       - ISSUE_INDEXER_TYPE=meilisearch
#       - ISSUE_INDEXER_CONN_STR=fulltextsearch:7700
#     # restart: always
#     # networks:
#     #   - gitea
#     volumes:
#       - ./volume/gitea:/data
#       - /etc/timezone:/etc/timezone:ro
#       - /etc/localtime:/etc/localtime:ro
#     ports:
#       - "3000:3000"
#       - "222:22"
#     depends_on:
#       - db
#       - keycloak
