apiVersion: v1
kind: Service
metadata:
  name: app-go
spec:
  ports:
  - name: http
    port: 3000
    targetPort: 80
  selector:
    app: app-go
  type: LoadBalancer
---
apiVersion: v1
kind: Service
metadata:
  name: app-python
spec:
  ports:
  - name: http
    port: 3000
    targetPort: 80
  selector:
    app: app-python
  type: LoadBalancer
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-go
spec:
  selector:
    matchLabels:
      app: app-go
  template:
    metadata:
      labels:
        app: app-go
    spec:
      containers:
      - command:
        - /app/webserver
        image: 192.168.0.10:32000/app-go
        name: app-go
        ports:
        - containerPort: 80
        resources:
          limits:
            cpu: "1"
            memory: 512Mi
          requests:
            cpu: 500m
            memory: 256Mi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-python
spec:
  selector:
    matchLabels:
      app: app-python
  template:
    metadata:
      labels:
        app: app-python
    spec:
      containers:
      - args:
        - --host
        - 0.0.0.0
        - --port
        - "80"
        command:
        - uvicorn
        - asgi:app
        image: 192.168.0.10:32000/app-python
        name: app-python
        ports:
        - containerPort: 80
